services:
  spark-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sparky:0.1
    container_name: sparky
    volumes:
      - ./sparky_project:/app/sparky_project
    ports:
      - "4040:4040"
    command: bash
    stdin_open: true
    tty: true
# volumes:
#   sparky:
#     name: sparky
#     driver: local
#     driver_opts:
#       device: $PWD/src
#       o: bind
#       type: none
